-- Auto-generated from schema-map-postgres.psd1 (map@9d3471b)
-- engine: postgres
-- table:  field_hash_policies
CREATE TABLE IF NOT EXISTS field_hash_policies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_table VARCHAR(64) NOT NULL,
  field_name   VARCHAR(64) NOT NULL,
  profile_id   BIGINT NOT NULL,               -- hash_profiles
  effective_from TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  notes TEXT NULL,
  CONSTRAINT uq_fhp UNIQUE (entity_table, field_name, effective_from)
);
